### PR TITLE
Add support for GNOME 40

### PR DESCRIPTION
**Pull request by TheWeirdDev**
This is a simple change to support GNOME 40 (and probably 3.38 too)

### CODE REVIEW

**Comment by flatcap** [comment]
@TheWeirdDev 
Thanks!  That works for me on Gnome 40.

**Comment by JumperLuko** [comment]
It worked, thanks

**Comment by OmiChrome** [comment]
someone do something for 47 :sob:

**Comment by maiself** [comment]
@NormTurtle, did something change in 47? Can you open a new issue and we can discuss it there?

I'm going to close this pull request because as it seems a bit outdated by now...

**Comment by OmiChrome** [comment]
@maiself im sorry i can't give much about on technical changes related to this project. 
im a just a user not a developer.

i want that extension to get worked.
to save my eyees in deep night when watching lectures with white boards.

**Comment by OmiChrome** [comment]
but, you can still see how other have some workarounds.
https://github.com/cg505/gnome-shell-grayscale-window
https://github.com/JackKenney/gnome-true-color-invert ( too old i guess?)

**Comment by maiself** [comment]
I just looked thru the 47 release notes and didn't see anything that might affect this extension, so it may be as simple as adding version 47 to `metadata.json`.

I see that the grayscale extension already has 47 listed, so it should be easy to compare for any changes. I don't know when I'll be able to upgrade to 47 to test tho.

If you know how to find it and edit it, adding the version to the list in `metadata.json` and then restarting may get things work right away. Otherwise please be patient until I can get around to updating things. Thanks for bringing this to my attention. I know how important dark mode and brightness inversion can be, I get headaches from bright screens, it's why I created this extension in the first place 🙂

**Comment by maiself** [comment]
@NormTurtle, just send a new version off for review, so should update automatically in a day or two when it passes. All that was needed was adding version 47 to the metadata file.

**Comment by OmiChrome** [comment]
Thank you so much

**Pull request closed without merging**
